### ISSUE TITLE
テキスト編集機能の改善

### ISSUE THREAD

**Issue by hiroto0222** [RecursionGroupQ/Mindmap#23]
- [ ] テキストのスタイリング -> FigJam を参考に

**Comment by harutas** [comment]
## 導入内容
- rich text editor のフレームワークであるdraft.jsとReact Draft Wysiwygを導入
- EditableText.tsxの代わりに<Editor />コンポーネントでテキストの編集スタイルの変更を行えるようにする。
## 問題
Konvaに描画する際にhtml elementを画像化したものを描画する必要がある。
→「html2canvas」ライブラリや「html to image」ライブラリを用いてcanvasに変換する
